TTH-3-features Features component
Codubee/TranslateNewsTTH4-5 pull request #1
Opened 2021-03-19 15:25 UTC by lilliemcmaster

* **Please check if the PR fulfills these requirements**
- [ ] The pull request title contains the ticket number in the title. For example [CB-1]

* **What kind of change does this PR introduce?** (Bug fix, new feature...)

* **What is the current behavior?What does the code do before you made the new changes?** 

* **What is the new behavior?**

* **Does this PR introduce a breaking change?** (What changes might users need to make in their application due to this PR? Run a new command?)

* **Other information**:

2021-03-23 15:14 UTC, Codubee submitted a review, later dismissed
Great work Lillie!

2021-03-24 21:32 UTC, jhagui7464 approved these changes, later dismissed
good job bud :)

2021-03-25 20:50 UTC, AruGyani submitted a review, later dismissed

2021-03-28 22:27 UTC, Codubee requested changes
One thing I forgot the mention before is to center the text please. To do so please create a stylesheet and import it into this file.

2021-04-02 21:54 UTC, Codubee approved these changes

2021-04-02 21:54 UTC, merged