TTH-2 Added base explanation banner
Codubee/TranslateNewsTTH4-5 pull request #5
Opened 2021-03-25 19:53 UTC by jhagui7464

…o switch between popular languages

* **Please check if the PR fulfills these requirements**
- [ ] The pull request title contains the ticket number in the title. For example [CB-1]

* **What kind of change does this PR introduce?** (Bug fix, new feature...)
We added an explanation component to show itself when the landing page is called, giving users a general idea on what the project is about.

* **What is the current behavior? What does the code do before you made the new changes?** 
There was no previous explanation component on the landing page.

* **What is the new behavior?**
There is an explanation banner on the landing page.

* **Does this PR introduce a breaking change?** (What changes might users need to make in their application due to this PR? Run a new command?)
No, the file is separate to what everyone else is on.

* **Other information**:
:)

2021-03-25 19:55 UTC, Codubee commented on frontend/src/components/Explanation.js
> +function ExplanationBox() {
Lets keep the file name the same as the component name.

2021-03-25 19:55 UTC, Codubee commented on frontend/src/components/Explanation.js
> +// This is where the explanation component will be created
Lets remove this comment as it no longer holds any value.

2021-03-25 19:56 UTC, Codubee commented on frontend/src/components/Explanation.js
> +        <div style={{ display: "flex" }}>
If you want some styling be sure to include a css file instead of inline styling. Its a little cleaner that way.

2021-03-25 19:57 UTC, Codubee requested changes
Great work Jose. I left some comments for discussion.

2021-03-28 22:22 UTC, Codubee commented on frontend/src/components/Explanation.js
> +                <a class="btn btn-primary btn-lg button" href="#Explanation.css" role="button" >Learn more</a>
We can actually remove this button completely as it doesnt do anything. Doing so also removes the needed Explanation .css

2021-03-29 15:04 UTC, nightveiI commented on frontend/src/components/Explanation.js
> +                <a class="btn btn-primary btn-lg button" href="#Explanation.css" role="button" >Learn more</a>
Originally thought we would use it later to link it to another component that shows the portraits of the teams, Will resolve asap.

2021-04-02 21:49 UTC, Codubee approved these changes, later dismissed

2021-04-02 21:50 UTC, merged